public class FoodItem {
    Public String IdOfFood;
    Public String TypeOfFood;
    public String Name;
    Public imageOfFood imageOfFood1;
    public thumbnailOfFood thumbnailOfFood1;
    public class imageOfFood{
        public string Url;
        public Integer width;
        public Integer height;
    }
    public class thumbnailOfFood{
        public string Url;
        public Integer width;
        public Integer height;
    }
    public static void parse(string json){
    }

}